kind: Service
apiVersion: v1
metadata:
  name: zipkin-es-svc
  labels:
    app: k8s-demo
    msvc: zipkin-es
spec:
  selector:
    app: k8s-demo
    msvc: zipkin-es
  ports:
  - port: 9200
    targetPort: 9200
  type: NodePort